### ISSUE TITLE
Unable to fetch external files namely, "covid19/train_exter.txt", "covid19/test_exter.txt"

### ISSUE THREAD

**Issue by gayu28** [williamscott701/Cross-SEAN#2]
Could not find these files as they are not created during feature extraction(extract_features.py). I am getting a file not found error, every time I am accessing ek_path and ekt_path. Can you provide my a solution as in how to create these files or how to access them?

```
Traceback (most recent call last):
  File "preprocess.py", line 121, in <module>
    ek_word_cntr = count_words(ek_path, args.vocab_size, args.tok, ek=True)
  File "preprocess.py", line 68, in count_words
    for _, words in read_file(path, tok, ek):
  File "preprocess.py", line 49, in read_file
    n_lines = count_lines(path)
  File "preprocess.py", line 44, in count_lines
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/covid19/train_exter.txt'

```

**Comment by williamscott701** [comment]
The released data do not contain the external knowledge scraped from the web. Please scrape the external knowledge and create a file.
